version: "3.8"

services:
  link-expander:
    build: .
    command: tail -f /dev/null # Keep the container running
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app # Mount the current directory to /app in the container
    networks:
      - lehlah
networks:
  lehlah:
    name: lehlah